name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 400 key.pem

      - name: Deploy via SSH
        run: |
          rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_DIR }}
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          if ! command -v docker &> /dev/null; then
            sudo dnf update -y
            sudo dnf install -y docker
            sudo systemctl enable --now docker

          fi
            cd ${{ secrets.APP_DIR }}
            sudo docker stop real-time-chat-app || true
            sudo docker rm real-time-chat-app || true
            sudo docker build -t real-time-chat-app .
            sudo docker run -d -p 3000:3000 --name real-time-chat-app real-time-chat-app
          EONG
          EOF
